### ISSUE TITLE
Dictionary compression support?

### ISSUE THREAD

**Issue by jarthod** [SpringMT/zstd-ruby#25]
Hi! I was looking for zstd with dictionary compression support in Ruby, I noticed this library doesn't support it (neither does `zstandard-ruby` apparently). Is it something you are interested in? I'm not sure if I'll have the courage to dive into the C API to write a PR but I might ;)

Dictionary requires to be pre-loaded to be able to compress and decompress efficiently so I was thinking about an API like this:
```ruby
# Training Dictionary
samples = [string1, string2, string3, ...]
dict = Zstd::Dictionary.train(samples, max_size: 10.kilobyte) # ZDICT_trainFromBuffer (also ZDICT_finalizeDictionary)?

# Using Dictionary
compressed_data = dict.compress(data) # ZSTD_compress_usingCDict
data = dict.decompress(compressed_data) # ZSTD_decompress_usingDDict

# Writing / Loading Dictionary
raw_dict = dict.to_s (get a binary string to store in database/file)
dict = Zstd::Dictionary.load(raw_dict) # ZSTD_CDict* ZSTD_createCDict (or ZSTD_createCDict_byReference)?
```

Let me know what you think?

**Comment by andrew-aladev** [comment]
This library has only basic bindings support, you can use [ruby-zstds](https://github.com/andrew-aladev/ruby-zstds), it supports streaming and dictionaries.

**Comment by jarthod** [comment]
Oh indeed, I totally missed this one, it doesn't come up well in google ;)
I also just noticed the https://github.com/DatekWireless/zstd library that seems to support it but looks abandoned. Anyway I'm gonna use this one then, thanks for bringing this to my attention !

**Comment by SpringMT** [comment]
Sorry for the delay, but we supported compression and decompression using dictionaries.
https://github.com/SpringMT/zstd-ruby/pull/49

Please see https://github.com/SpringMT/zstd-ruby#usage.

(Dictionary generation is not yet supported 🙇 )

**Comment by jarthod** [comment]
@SpringMT That is good new, thanks :)
