### ISSUE TITLE
Default compression level

### ISSUE THREAD

**Issue by p-mongo** [SpringMT/zstd-ruby#28]
Hi,

I was researching the default compression level that zstd uses and I saw that:

- zstd-ruby uses 0
- https://www.mankier.com/1/zstd uses 3

Was 0 chosen intentionally? If yes where can one find more information about this?

**Comment by SpringMT** [comment]
Sorry for the late reply.

The compression level 0 means using default compression level(ZSTD_CLEVEL_DEFAULT).
https://github.com/SpringMT/zstd-ruby/blob/master/ext/zstdruby/zstdruby.c#L22

Ref : http://facebook.github.io/zstd/zstd_manual.html#Chapter5

zstd-ruby use ZSTD_compress.

ZSTD_compress
https://github.com/facebook/zstd/blob/bb6ca687137a976b4daa22349ab4aa1e53336fe9/lib/compress/zstd_compress.c#L3641-L3658

ZSTD_compress calls ZSTD_compressCCtx and ZSTD_compress_usingDict.

https://github.com/facebook/zstd/blob/bb6ca687137a976b4daa22349ab4aa1e53336fe9/lib/compress/zstd_compress.c#L3631-L3639

https://github.com/facebook/zstd/blob/bb6ca687137a976b4daa22349ab4aa1e53336fe9/lib/compress/zstd_compress.c#L3615-L3629

ZSTD_compress_usingDict convert compression level 0 to ZSTD_CLEVEL_DEFAULT 3.
https://github.com/facebook/zstd/blob/bb6ca687137a976b4daa22349ab4aa1e53336fe9/lib/compress/zstd_compress.c#L3625

**Comment by SpringMT** [comment]
Is it clear that using ZSTD_CLEVEL_DEFAULT instead of compression level 0 ?

**Comment by p-mongo** [comment]
Thank you I believe the current behavior works for me.
