### ISSUE TITLE
Regression when decompressing an empty string in `zstd` 1.5.2.3

### ISSUE THREAD

**Issue by agalloch** [SpringMT/zstd-ruby#51]
Hello, thank you for maintaining this awesome gem! 👏 

When upgrading `zstd-ruby` from 1.5.2.2 to 1.5.2.3 I've encountered the following difference in `decompress` behaviour:
```
# Expected behaviour (as it was in versions < v1.5.2.3)

irb> Zstd.decompress ''
=> ""
```
vs.
```
# Actual behaviour

irb> Zstd.decompress ''
RuntimeError: not compressed by zstd: Unspecified error code
```
Since it's the same upstream version of `zstd` library (https://github.com/facebook/zstd/releases/tag/v1.5.2), this seems like a regression in the gem.

Am I missing something?

**Comment by SpringMT** [comment]
In `v1.5.2.3`, zstd decompression frame check is strictly.
https://github.com/SpringMT/zstd-ruby/blob/main/ext/zstdruby/zstdruby.c#L121-L124

Previously using `ZSTD_getDecompressedSize` when check decompression string, but this method is obsolete.
So, v1.5.2.3 zstd-ruby gem uses `ZSTD_getFrameContentSize`.
https://raw.githack.com/facebook/zstd/release/doc/zstd_manual.html#Chapter3

In `ZSTD_getFrameContentSize`, an empty string with decompression is invalid, so in the spec, an empty string decompression should have been treated as an error.
The example from the zstd sample.
https://github.com/facebook/zstd/blob/dev/examples/simple_decompression.c#L27

It is not regression but breaking backward compatibility.

Is there any inconvenience?

**Comment by agalloch** [comment]
Hello @SpringMT, I'm not sure whether `zstd-ruby` gem uses semantic versioning but if it does, it's unusual to introduce backward incompatibility with a patch update such as `1.5.2.2 -> 1.5.2.3`.

Do you recommend I use `Zstd::StreamingDecompress` when the source could be a blank string? 🙂

**Comment by SpringMT** [comment]
I'm considering again whether it is correct that `Zstd::StreamingDecompress` and `Zstd.decompress` is different behavior.

**Comment by SpringMT** [comment]
First of all, I add breaking change about an empty string decompress to the release note.
https://github.com/SpringMT/zstd-ruby/releases/tag/v1.5.2.3
