### ISSUE TITLE
[feature] Support Streaming Compression/Decompression with Dictionary

### ISSUE THREAD

**Issue by AndrewCEmil** [SpringMT/zstd-ruby#61]
Hi! I noticed that this library supports streaming compression/decompression and also dictionary compression/decompression. But it doesn't seem to support streaming compression/decompression using a dictionary.

I'd to add support for this. Please let me know if you have any thoughts on implementation or interface for this. I'm currently working through the changes in my forked repo: https://github.com/AndrewCEmil/zstd-ruby.

Ideally I would like to support:
- Streaming compression/decompression using raw dictionary bytes
- Streaming compression/decompression using processed dictionary objects (`ZSTD_CDict` and `ZSTD_DDict`)
- The ability to process dictionary bytes. This would effectively allow a user to call `ZSTD_CreateCDict` and `ZSTD_CreateDDict` and receive the output in ruby. They could then store the processed and use it later rather than having to process it each time, which according to the zstd docs (http://facebook.github.io/zstd/zstd_manual.html) is a costly operation.

Initially, I'll probably just implement the first feature (raw dictionary bytes), but I'll try to leave room in the interface to support caching for later implementation.

**Comment by SpringMT** [comment]
Thanks for the request.
I have not been able to find the time to implement it now.
Sorry about that.
I am planning to respond around the end of the year.

**Comment by AndrewCEmil** [comment]
No worries! I have gone ahead and opened https://github.com/SpringMT/zstd-ruby/pull/62/files, which should cover the first part ("Streaming compression/decompression using raw dictionary bytes"). Thanks!

**Comment by SpringMT** [comment]
I have unified the handling of dictionaries. https://github.com/SpringMT/zstd-ruby/pull/77

**Comment by SpringMT** [comment]
Release v1.5.6.2  https://rubygems.org/gems/zstd-ruby/versions/1.5.6.2
