### ISSUE TITLE
Compatibility Inquiry: [zstd-ruby] 1.5.5.0  with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [SpringMT/zstd-ruby#63]
Hi,

I'm seeking confirmation regarding the compatibility of the [zstd-ruby] 1.5.5.0 with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on https://github.com/SpringMT/zstd-ruby/blob/main/.github/workflows/ruby.yml the code specified the ruby-version: ['2.7', '3.0', '3.1', '3.2']. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by SpringMT** [comment]
Add '3.3' for GitHub Actions ruby-version matrix and pass all tests.

**Comment by sydverisk** [comment]
Thanks! for the response @SpringMT I appreciate it!
